### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by sangjunp4rk** [silverFog/prj-rev-bwfs-dasmoto#5]
Summary Grade: Exceeds Expectations

Good job with your code! I really like the use of indentation and whitespace in your html code! Makes your code very easy to read! Also, good decisions on the classes and ids name. It makes it very clear what its purpose is and makes grouping your sections very effective. These organizational skills come in handy as you expand your code. Great start to the Ready program!
 
I included a few notes in both the html and css files for you to think more critically about. First, make sure to use the html & sign instead of just &, which is `&amp;.` This is just a convention. Finally, your lines are a bit long right now. Try splitting this into new lines so it's easier to read on one screen without scrolling. Convention is usually ~79 characters per line.

**Comment by silverFog** [comment]
Thanks for the actionable comments! I was honestly quite apprehensive about the whole idea of someone going through my code, but it turned out to be nothing. I went ahead and applied the changes suggested, turns out the auto-wrap feature of my editor doesn't actually enter the carriage return to the code so those long lines get posted. Thanks again for your time and kind words.
